---
- hosts: web
  vars:
    hostname: HOST_NAME
    environtment: production
    ruby_version: 2.2.0
    user_name: USER_NAME
    postgres_user: POSTGRES_USER_NAME
  roles:
    - common
    - swap
    - postgresql
    - rvm
    - swap
    - nginx
    - rails
    - newrelic
    - iptables
