---
- name: create swap directory
  register: mk_swap_dir
  sudo: true
  shell: mkdir /var/swap
  ignore_errors: yes
- name: create swap file
  sudo: true
  shell: dd if=/dev/zero of=/var/swap/swap0 bs=1M count=2048
  when: mk_swap_dir|success
- name: set permission to swap file
  sudo: true
  shell: chmod 600 /var/swap/swap0
  when: mk_swap_dir|success
- name: mkswap settings
  sudo: true
  shell: mkswap /var/swap/swap0 && swapon /var/swap/swap0
  when: mk_swap_dir|success
- name: set boot settings
  sudo: true
  shell: echo '/var/swap/swap0 swap swap defaults 0 0' >> /etc/fstab
  when: mk_swap_dir|success